### ISSUE TITLE
This assumes minimization.

### ISSUE THREAD

**Issue by light-weaver** [industrial-optimization-group/desdeo-problem#6]
https://github.com/industrial-optimization-group/desdeo-problem/blob/96891b8f648f3ee24f23cf94bb7629d01958b572/desdeo_problem/Problem.py#L492

I think the user should have the option to specify whether they want to maximize or minimize. This can be done in two ways. Either problem.evaluate should return (objectives, constraints, fitness, uncertainity), where fitness = objective value multiplied by +/- one depending on whether to minimize or maximize, OR, the fitness calculation should be done in the optimization methods.

This should also enable us to make visualizations better.

**Comment by gialmisi** [comment]
I have assumed that the problem is always per-processed, that is, the data is normalized and the objectives (values of) are expressed to work with the assumption of minimization. This was my vision.

However, if it is more practical, which it probably is, we should implement the kind of functionality you suggested. I'd like if we can keep the assumption of minimization in as many levels of the framework as possible, just to keep things simple. So your first suggestion to return a fitness value in evaluate, is more appealing to me.

**Comment by light-weaver** [comment]
In that case, perhaps we should start returning dicts or named tuples because there are so many outputs
